package com.chinasofti.mybatis;

import com.chinasofti.pojo.DocumentInf;

public interface DocumentInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insert(DocumentInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insertSelective(DocumentInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    DocumentInf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKeySelective(DocumentInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKey(DocumentInf record);
}