package com.chinasofti.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinasofti.pojo.DocumentInf;
import com.chinasofti.pojo.Page;

public interface DocumentInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insert(DocumentInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insertSelective(DocumentInf record);
    List<DocumentInf> getDocs(@Param("title") String title,@Param("page") Page page);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    DocumentInf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKeySelective(DocumentInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKey(DocumentInf record);
}