package com.chinasofti.mybatis;

import com.chinasofti.pojo.JobInf;

public interface JobInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insert(JobInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insertSelective(JobInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    JobInf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKeySelective(JobInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKey(JobInf record);
}