package com.chinasofti.mybatis;

import com.chinasofti.pojo.NoticeInf;

public interface NoticeInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insert(NoticeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int insertSelective(NoticeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    NoticeInf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKeySelective(NoticeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(NoticeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    int updateByPrimaryKey(NoticeInf record);
}