package com.chinasofti.pojo;

public class DeptInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_inf.ID
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_inf.NAME
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_inf.REMARK
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_inf.ID
     *
     * @return the value of dept_inf.ID
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_inf.ID
     *
     * @param id the value for dept_inf.ID
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_inf.NAME
     *
     * @return the value of dept_inf.NAME
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getName() {
        return name;
    }

    @Override
	public String toString() {
		return "DeptInf [id=" + id + ", name=" + name + ", remark=" + remark + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_inf.NAME
     *
     * @param name the value for dept_inf.NAME
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_inf.REMARK
     *
     * @return the value of dept_inf.REMARK
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    public DeptInf(String name, String remark) {
		super();
		this.name = name;
		this.remark = remark;
	}

	public DeptInf() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_inf.REMARK
     *
     * @param remark the value for dept_inf.REMARK
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}