package com.chinasofti.pojo;

import java.util.Date;

public class UserInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.ID
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.loginname
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.PASSWORD
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String password;

    @Override
	public String toString() {
		return "UserInf [id=" + id + ", loginname=" + loginname + ", password=" + password + ", status=" + status
				+ ", createdate=" + createdate + ", username=" + username + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.STATUS
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.createdate
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.username
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.faceurl
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String faceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.facepath
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    private String facepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.ID
     *
     * @return the value of user_inf.ID
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.ID
     *
     * @param id the value for user_inf.ID
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.loginname
     *
     * @return the value of user_inf.loginname
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.loginname
     *
     * @param loginname the value for user_inf.loginname
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.PASSWORD
     *
     * @return the value of user_inf.PASSWORD
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.PASSWORD
     *
     * @param password the value for user_inf.PASSWORD
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.STATUS
     *
     * @return the value of user_inf.STATUS
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.STATUS
     *
     * @param status the value for user_inf.STATUS
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.createdate
     *
     * @return the value of user_inf.createdate
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.createdate
     *
     * @param createdate the value for user_inf.createdate
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.username
     *
     * @return the value of user_inf.username
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.username
     *
     * @param username the value for user_inf.username
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.faceurl
     *
     * @return the value of user_inf.faceurl
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getFaceurl() {
        return faceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.faceurl
     *
     * @param faceurl the value for user_inf.faceurl
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setFaceurl(String faceurl) {
        this.faceurl = faceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.facepath
     *
     * @return the value of user_inf.facepath
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public String getFacepath() {
        return facepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.facepath
     *
     * @param facepath the value for user_inf.facepath
     *
     * @mbggenerated Tue Jun 15 13:00:02 CST 2021
     */
    public void setFacepath(String facepath) {
        this.facepath = facepath;
    }
}